// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLogPath() {
  return window['go']['app']['App']['GetLogPath']();
}

export function GetPowerState() {
  return window['go']['app']['App']['GetPowerState']();
}

export function GetScanedBaseStations() {
  return window['go']['app']['App']['GetScanedBaseStations']();
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetStatus() {
  return window['go']['app']['App']['GetStatus']();
}

export function HideWindow() {
  return window['go']['app']['App']['HideWindow']();
}

export function Identify(arg1) {
  return window['go']['app']['App']['Identify'](arg1);
}

export function IsScanning() {
  return window['go']['app']['App']['IsScanning']();
}

export function OnSecondInstanceLaunch(arg1) {
  return window['go']['app']['App']['OnSecondInstanceLaunch'](arg1);
}

export function Quit() {
  return window['go']['app']['App']['Quit']();
}

export function ReadLogs(arg1) {
  return window['go']['app']['App']['ReadLogs'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function SetDevices(arg1) {
  return window['go']['app']['App']['SetDevices'](arg1);
}

export function SetPower(arg1) {
  return window['go']['app']['App']['SetPower'](arg1);
}

export function SetPowerSome(arg1, arg2) {
  return window['go']['app']['App']['SetPowerSome'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['app']['App']['ShowWindow']();
}

export function StartSVC() {
  return window['go']['app']['App']['StartSVC']();
}

export function StartScan() {
  return window['go']['app']['App']['StartScan']();
}

export function StopScan() {
  return window['go']['app']['App']['StopScan']();
}
