// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {settings} from '../models';
import {options} from '../models';

export function GetLogPath():Promise<string>;

export function GetPowerState():Promise<Record<string, string>>;

export function GetScanedBaseStations():Promise<Array<service.BaseStation>>;

export function GetSettings():Promise<settings.Content>;

export function GetStatus():Promise<service.Status>;

export function HideWindow():Promise<void>;

export function Identify(arg1:string):Promise<void>;

export function IsScanning():Promise<boolean>;

export function OnSecondInstanceLaunch(arg1:options.SecondInstanceData):Promise<void>;

export function Quit():Promise<void>;

export function ReadLogs(arg1:number):Promise<Array<string>>;

export function SaveSettings(arg1:settings.Content):Promise<void>;

export function SetDevices(arg1:Array<settings.BaseStation>):Promise<void>;

export function SetPower(arg1:boolean):Promise<void>;

export function SetPowerSome(arg1:boolean,arg2:Array<string>):Promise<void>;

export function ShowWindow():Promise<void>;

export function StartSVC():Promise<void>;

export function StartScan():Promise<void>;

export function StopScan():Promise<void>;
